#!/bin/bash
set -e

ROOTDIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [ARGUMENT]"
    echo "  setup"
    echo "  start"
    echo "  stop"
    echo "  clean"
    echo "  restart [CN_ID]"
    echo "  refresh"
    exit 22
fi

if [ "$1" == "restart" ] && [ "$#" -lt 2 ]; then
    echo "Usage: $0 restart [CN_ID, 0 for all cn nodes]"
    exit 1
fi

FN="cmd/$1.sh"
[ -f $FN ] && source "$FN"
HOMIOUTPUT=${2:-"homi-output"}
HOMIOUTPUT="$ROOTDIR/$HOMIOUTPUT"

case "$1" in
  "setup")
    setup
    ;;
  "start")
    start
    ;;
  "stop")
    stop
    ;;
  "clean")
    clean
    ;;
  "restart")
    restart $2
    ;;
  "refresh")
    refresh
    ;;
  "upgrade")
    upgrade
    ;;
  "init")
    init
    ;;
  *)
    echo "no such option"
    exit 1
    ;;
esac
